// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mover from "./Mover.res.mjs";

function make(x, y, height, width, vel, mass, damping, color) {
  var body = Mover.make(x, y, vel, mass, damping);
  var color$1 = color !== undefined ? color : "#000000";
  return {
          body: body,
          height: height,
          width: width,
          color: color$1
        };
}

function getPosition(ball) {
  return Mover.getPosition(ball.body);
}

function display(ball, p) {
  var pos = Mover.getPosition(ball.body);
  p.fill(255);
  p.ellipse(pos.x, pos.y, ball.width, undefined);
}

function update(ball, p) {
  Mover.update(ball.body, undefined);
}

var Vector;

export {
  Vector ,
  make ,
  getPosition ,
  display ,
  update ,
}
/* No side effect */
