// Generated by ReScript, PLEASE EDIT WITH CARE


function staticDivide(vector, arg) {
  return Vector.div(vector, arg._0);
}

function staticSub(vector, arg) {
  return Vector.sub(vector, arg._0);
}

var Vector = {
  staticDivide: staticDivide,
  staticSub: staticSub
};

export {
  Vector ,
}
/* No side effect */
